[tool.poetry]
name = "pydala"
version = "0.1.0"
description = ""
authors = ["Volker Lorrmann <volker.lorrmann@gmail.com>"]
readme = "README.md"
packages = [{include = "pydala", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pathlib = "^1.0.1"
duckdb = "^0.5.1"
pandas = "1.5.1"
polars = "0.14.24"
joblib = "^1.2.0"
s3fs = "2022.10.0"
pyarrow = "10.0.0"
fsspec = "^2022.8.2"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
