[tool.poetry]
name = "pydatalake"
version = "0.1.0"
description = ""
authors = ["Volker Lorrmann <volker.lorrmann@gmail.com>"]
readme = "README.md"
packages = [{include = "pydatalake", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
duckdb = "^0.5.0"
pyarrow = "^9.0.0"
pandas = "^1.4.4"
pathlib = "^1.0.1"
polars = "^0.14.18"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
